RUMOR_INT_TO_CLASS = {
    1: "Dirty Voter Rolls",
    5: "Dirty Voter Rolls",
    2: "Ballot Mail-In Fraud",
    3: "Ballot Mail-In Fraud",
    10:"Ballot Mail-In Fraud",
    11:"Ballot Mail-In Fraud",
    6: "Voter Registration Fraud",
    7: "Voter Registration Fraud",
    9: "Voter Registration Fraud",
    4: "Voting Technology Issues",
    8: "Voting Technology Issues",
    12:"Voting Technology Issues",
    13:"Voting Technology Issues",
    16:"Voting Technology Issues",
    14:"Voter Intimidation Tactics",
    15:"Voter Intimidation Tactics",
}


RUMORS = {
   "Election Integrity Undermined": "Claims suggesting the election process is fundamentally unfair or compromised.",
   "Dirty Voter Rolls": "Election officials don't clean the voter rolls. The voter rolls are inaccurate and they are not updated.",
   "Ballot Mail-In Fraud": "People can easily violate the integrity of the mail-in/absentee ballot request process to receive and cast unauthorized mail-in/absentee ballots, or prevent authorized voters from voting successfully in person.",
   "Drop Box Tampering": "Drop boxes used by election officials to collect returned mail-in/absentee ballots can be easily tampered with, stolen, or destroyed.",
   "Software Security": "Voting system software is not reviewed or tested and can be easily manipulated.",
   "Dead Voters": "Votes are being cast on behalf of dead people and these votes are being counted.",
   "Voter Registration Data Breach": "Someone possessing or posting voter registration data means voter registration databases have been hacked.",
   "Voter Registration Website Outage": "An online voter registration website experiences an outage and claims are made the election has been compromised.",
   "Hacking into Jurisdictions": "If state or local jurisdiction information technology (IT) has been compromised, the election results cannot be trusted.",
   "Voter Registration Manipulation": "Videos, images or emails suggesting voter registration information is being manipulated means voters will not be able to vote.",
   "Extra Mail-in Ballots": "A malicious actor can easily defraud an election by printing and sending in extra mail-in ballots.",
   "Ballot FWAB Fraud": "A malicious actor can easily defraud an election using the Federal Write-In Absentee Ballot (FWAB).",
   "Ballot Scanner Issues": "Problems with ballot scanners at my voting site mean that my ballot won't be counted.",
   "Ballot Writing Instrument Issue": "Poll workers gave specific writing instruments, such as Sharpies, only to specific voters to cause their ballots to be rejected.",
   "Voter Intimidation Tactics": "Observers in the polling place are permitted to intimidate voters, campaign, and interfere with voting.",
   "Nonexistent Vote Disclosure": "Someone is claiming to know who I voted for.",
   "Polling Lookup Outage": "If polling place lookup sites experience an outage, election infrastructure must have been compromised.",
}

RUMORS_TITLELESS = {
    1: "Election officials don't clean the voter rolls. The voter rolls are inaccurate and they are not updated.",
    2: "People can easily violate the integrity of the mail-in/absentee ballot request process to receive and cast unauthorized mail-in/absentee ballots, or prevent authorized voters from voting successfully in person.",
    3: "Drop boxes used by election officials to collect returned mail-in/absentee ballots can be easily tampered with, stolen, or destroyed.",
    4: "Voting system software is not reviewed or tested and can be easily manipulated.",
    5: "Votes are being cast on behalf of dead people and these votes are being counted.",
    6: "Someone possessing or posting voter registration data means voter registration databases have been hacked.",
    7: "An online voter registration website experiences an outage and claims are made the election has been compromised.",
    8: "If state or local jurisdiction information technology (IT) has been compromised, the election results cannot be trusted.",
    9: "Videos, images or emails suggesting voter registration information is being manipulated means voters will not be able to vote.",
    10: "A malicious actor can easily defraud an election by printing and sending in extra mail-in ballots.",
    11: "A malicious actor can easily defraud an election using the Federal Write-In Absentee Ballot (FWAB).",
    12: "Problems with ballot scanners at my voting site mean that my ballot won't be counted.",
    13: "Poll workers gave specific writing instruments, such as Sharpies, only to specific voters to cause their ballots to be rejected.",
    14: "Observers in the polling place are permitted to intimidate voters, campaign, and interfere with voting.",
    15: "Someone is claiming to know who I voted for.",
    16: "If polling place lookup sites experience an outage, election infrastructure must have been compromised.",
}


RUMORS_NUMBERED = {
   1: "Dirty Voter Rolls: Election officials don't clean the voter rolls. The voter rolls are inaccurate and they are not updated.",
   2: "Ballot Mail-In Fraud: People can easily violate the integrity of the mail-in/absentee ballot request process to receive and cast unauthorized mail-in/absentee ballots, or prevent authorized voters from voting successfully in person.",
   3: "Drop Box Tampering: Drop boxes used by election officials to collect returned mail-in/absentee ballots can be easily tampered with, stolen, or destroyed.",
   4: "Software Security: Voting system software is not reviewed or tested and can be easily manipulated.",
   5: "Dead Voters: Votes are being cast on behalf of dead people and these votes are being counted.",
   6: "Voter Registration Data Breach: Someone possessing or posting voter registration data means voter registration databases have been hacked.",
   7: "Voter Registration Website Outage: An online voter registration website experiences an outage and claims are made the election has been compromised.",
   8: "Hacking into Jurisdictions: If state or local jurisdiction information technology (IT) has been compromised, the election results cannot be trusted.",
   9: "Voter Registration Manipulation: Videos, images or emails suggesting voter registration information is being manipulated means voters will not be able to vote.",
   10: "Extra Mail-in Ballots: A malicious actor can easily defraud an election by printing and sending in extra mail-in ballots.",
   11: "Ballot FWAB Fraud: A malicious actor can easily defraud an election using the Federal Write-In Absentee Ballot (FWAB).",
   12: "Ballot Scanner Issues: Problems with ballot scanners at my voting site mean that my ballot won't be counted.",
   13: "Ballot Writing Instrument Issue: Poll workers gave specific writing instruments, such as Sharpies, only to specific voters to cause their ballots to be rejected.",
   14: "Voter Intimidation Tactics: Observers in the polling place are permitted to intimidate voters, campaign, and interfere with voting.",
   15: "Nonexistent Vote Disclosure: Someone is claiming to know who I voted for.",
   16: "Polling Lookup Outage: If polling place lookup sites experience an outage, election infrastructure must have been compromised.",
}